name: production
url: https://dineai-pos.com
protection_rules:
  required_reviewers:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  required_status_checks:
    strict: true
    contexts:
      - "Flutter Build & Test"
      - "Deploy to Staging"
  required_deployment_environments:
    - staging
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false 